name: Publish to Maven
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish package
        run: gradle publish
        env:
          KITUIN_USERNAME: ${{ secrets.KITUIN_USERNAME }}
          KITUIN_PASSWORD: ${{ secrets.KITUIN_PASSWORD }}